### ISSUE TITLE
[Peer Testing] Wrong error message

### ISSUE THREAD

**Issue by tiffanyliu0220** [AY2324S2-CS2113-F15-2/tp#235]
when a positive large index is typed for the 'calories delete' command, it shows this even though it is a positive number.
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/8d276be0-a149-4b89-a2ae-20b97cf6736c)

**Comment by tiffanyliu0220** [comment]
and shows this when the index is negative
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/69453e5e-905d-4db9-a5b2-85f6b549a619)

**Comment by rexyyong** [comment]
Maybe i should write something like please enter valid positive integer within range of all the calories id

**Comment by paturikarthik** [comment]
yes, please!

**Comment by rexyyong** [comment]
@paturikarthik  for the negative one i decided not to change the exception message because it is correct that caloriesID -1 could not be found. 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/a22a55dc-9450-4ab4-8cd6-6a32d97e4322)

For the case of too big caloriesID, is this sufficient? Cuz we follow this guidelines for integer overflow right
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/d185bb97-d99f-4215-92b3-29a0ca33d3fb)

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/4f2be9b3-cda8-4b66-a65c-77bf464a1d5d)
